# Generated by Django 4.2.3 on 2023-07-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("kbins", "KB손해"),
                            ("kblife", "KB생명"),
                            ("no_aff", "소속없음"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "tag"), name="product_name_tag"
            ),
        ),
    ]
