# Generated by Django 4.2.3 on 2023-07-04 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                (
                    "calendar",
                    models.CharField(
                        choices=[("lunar", "음력"), ("solar", "양력")],
                        default="solar",
                        max_length=5,
                    ),
                ),
                ("enrollment_date", models.DateField(null=True)),
                (
                    "enticement_status",
                    models.CharField(
                        choices=[
                            ("pre-progress", "유치예정"),
                            ("in-progress", "유치중"),
                            ("progress-complete", "유치완료"),
                        ],
                        default="in-progress",
                        max_length=20,
                    ),
                ),
                ("flag", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, max_length=4000)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_note",
            },
        ),
    ]
