version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: rapport-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - rapport-mysql:/var/lib/mysql
      - ./infra/mysql/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    restart: always

  api:
    build: .
    container_name: rapport-api
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env.local
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.deploy
    depends_on:
      - rabbitmq
      - db
      - worker

  rabbitmq:
    image: rabbitmq:management
    container_name: rapport-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /celery_entrypoint.sh
    env_file:
      - .env.local
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.deploy
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
      - db

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - FLOWER_PORT=5555
      - FLOWER_PERSISTENT=False
      - FLOWER_PURGE_OFFLINE_WORKERS=10
    ports:
      - "5555:5555"

  nginx:
    build: ./infra/nginx
    container_name: rapport-nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

volumes:
  rapport-mysql: