# Generated by Django 4.2.3 on 2023-07-04 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("has_end_time", models.BooleanField(default=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_schedule",
            },
        ),
    ]
